### ISSUE TITLE
LoopingPagerAdapter bindview call twice

### ISSUE THREAD

**Issue by siavash-sajjad** [siralam/LoopingViewPager#10]
hi
i use your library in my application. i have a calendar and add one day to calendar in bindview method, but this method call twice and add two day to calendar.
how to fix this problem?
thank you and sorry for poor my english

**Comment by xdmilaxd** [comment]
I have simillar issue. Firstly I create my adapter with list which contains 4 elements. It works great. But now I would like to add/remove pages from my view pager at runtime so  I add new list item to my list and then I call adapter.notifyDataSetChanged() or adapter.setItemList(newItemList) and the result is the same. I expect to have in this case 5 elements on my view pager but I have 9. So it added whole list to previous one. Any ideas how to solve it?
