### ISSUE TITLE
Rtl support

### ISSUE THREAD

**Issue by H-Zandi** [siralam/LoopingViewPager#12]
how support rtl? or reverse autoScroll?

**Comment by siralam** [comment]
RTL should not be a problem. But it currently does not support changing the scroll direction yet (Since it would require a custom transformation. The existing transformation is using the default one provided by ViewPager)

**Comment by H-Zandi** [comment]
I wrote custom image slider with viewpager and PagerAdapter like this and use android:rotation="180" for item and view pager but it didn't work in android 9 (Pie) anymore :(

**Comment by siralam** [comment]
Adding rotation="180" as far as I know is not the correct way to do this... RTL is not simply mirroring everything.... e.g. Image should not be mirrored
