### ISSUE TITLE
androidx support

### ISSUE THREAD

**Issue by pparkppark** [siralam/LoopingViewPager#14]
When I migrated my project to Androidx, the compiler failed with an incorrect cast in setadapter. I built it temporarily via enablejetifier, but it shows the wrong behavior in the instanceof reserved words. I want to know when Androidx support.

**Comment by siralam** [comment]
Do not have experience on Android X yet, will take a look at this in the future.

**Comment by pparkppark** [comment]
@siralam, see the pull request please

**Comment by siralam** [comment]
Merged #15
