### ISSUE TITLE
Add support for item resizing

### ISSUE THREAD

**Issue by dfbarone** [siralam/LoopingViewPager#17]
I want to be able to resize viewpager items when aspect ratio is enabled and clipToPadding is true. For example if an item maintains an aspect ratio (4:3) of its own it should resize to fit into the viewpager (16:9) in this case. 

I have included a diff with changes. This is somewhat similar to my last PR for wrap_content, but instead of an item resizing to take padding into account, the item will simply be increasing the viewpager padding so that it will fit fully into the viewpager.  

https://github.com/siralam/LoopingViewPager/compare/master...dfbarone:loopingviewpager_onmeasure_aspectratio_padding?expand=1

![screenshot_1543720442](https://user-images.githubusercontent.com/17164537/49335302-fe0f4000-f5b8-11e8-899b-05dbd38e63d2.png)

**Comment by siralam** [comment]
Implemented in v1.2.0. Thanks again @dfbarone !
