### ISSUE TITLE
Move rigth away or move too fast at the beginning and at the end

### ISSUE THREAD

**Issue by firdaus1453** [siralam/LoopingViewPager#28]
I got this behavior, if image at beginning or end, image not stop, but move right away, this not good, can you help me, solve this problem

Maybe this gif can make you understand

![issuauto](https://user-images.githubusercontent.com/20089079/75338100-c75dcd80-58c0-11ea-8683-7c2eac8cc417.gif)

You see,  after image at end, they will change too fast and move to second image, not first image, you can see on dot indicator, and vice versa

This is my Adapter
![image](https://user-images.githubusercontent.com/20089079/75348569-b8354a80-58d5-11ea-8bb5-7886f778ef96.png)

This is my xml
![image](https://user-images.githubusercontent.com/20089079/75342691-7d2d1a00-58c9-11ea-949a-5aecb0843428.png)

This is when i set adapter
![image](https://user-images.githubusercontent.com/20089079/75338300-0f7cf000-58c1-11ea-874a-722da60332d0.png)

This is when i replace data
![image](https://user-images.githubusercontent.com/20089079/75338378-32a79f80-58c1-11ea-9e31-0083a7bcc9c3.png)

Hope my question clear, CMIIW
This library is very cool, i can use page indicator what i want, keep this library live bro 😄

**Comment by mochadwi** [comment]
You should try to look at the `LoopingViewPager` class instead, to check when `first` or `last` item occurs. @firdaus1453

**Comment by firdaus1453** [comment]
> You should try to look at the `LoopingViewPager` class instead, to check when `first` or `last` item occurred. @firdaus1453

I think, both, because i try to move to end with swipe, automatically move so fast to second image, and otherwise

**Comment by firdaus1453** [comment]
Oke i change my code, not use replaceData, i use constructor adapter to get data

![image](https://user-images.githubusercontent.com/20089079/75357536-1cf7a180-58e4-11ea-8bf8-b2cc8b69b3ea.png)

And i got this, 
![issuauto2](https://user-images.githubusercontent.com/20089079/75357746-71028600-58e4-11ea-8b89-b2a96960d36f.gif)

This normal, because this library have behavior like that
/**
 * A Pager Adapter that supports infinite loop.
 * This is achieved by adding a fake item at both beginning and the last,
 * And then silently changing to the same, real item, thus looks like infinite.
 */

And my bad, not read carefully in documentation, if you want to add dots indicator library, you dots indicator library must allow you to change total number dot in indicator

I will search different dots indicator library or i not use this library

Oke, thanks for response, i will close this issue

**Comment by alokraj68** [comment]
We still getting this issue. what to do to fix this issue?
