### ISSUE TITLE
Auto-scroll doesn't start automatically

### ISSUE THREAD

**Issue by tapandesai** [siralam/LoopingViewPager#29]
Auto-scroll doesn't start automatically when the screen is loaded, but once I swipe to next item manually then it starts working as expected. 

Here is the xml declaration

`<com.asksira.loopingviewpager.LoopingViewPager
            android:id="@+id/vpOffers"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:clipToPadding="false"
            app:autoScroll="true"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:scrollInterval="5000"
            app:viewpagerAspectRatio="1.78" />`

**Comment by siralam** [comment]
If you are using it in ConstraintLayout, I think you should specify width = 0dp and give it constraintEnd_toEndOf = parent. See if this solves the problem?

**Comment by tapandesai** [comment]
Thanks for the quick response. I tried what you suggested but it didn't work

**Comment by siralam** [comment]
Hm, not idea now since I cannot reproduce this. Would you mind post your whole Activity / Fragment and the full xml which contains the LoopingViewPager?
