### ISSUE TITLE
How can i control the speed of sliding page

### ISSUE THREAD

**Issue by varunjain0888** [siralam/LoopingViewPager#30]
How can i control the speed of sliding page

**Comment by AndreiApostoiu** [comment]
Up

**Comment by cirnoftw** [comment]
It's actually a ViewPager issue, which LoopingViewPager is based on:
https://stackoverflow.com/questions/8155257
ViewPager doesn't allow you to change transition speed, so you'll likely have to override that behaviour yourself by implementing your own pager.

**Comment by siralam** [comment]
Yes, @cirnoftw has answered for me. Thank you!
