### ISSUE TITLE
Show blank slide at first when scrolling to right from last slide to next 

### ISSUE THREAD

**Issue by vimal1695** [siralam/LoopingViewPager#44]
If there is 5 slide and when i slide from 4th to 5th . The first item will be a blank. This happen when clipToPadding=false and ViewPager  able to peek adjacent items. 

https://user-images.githubusercontent.com/11749730/117976504-7d3dfc00-b34d-11eb-9798-c553d5126c6b.mp4

**Comment by siralam** [comment]
As I have mentioned in my readme:
```
(But first and last item will appear only after scroll state is idle)
```

This is an unavoiable behaviour if you have to peek adjacent items, due to the fundamental apporach of "infinite". If this is not acceptable, I am sorry but you will have to find other appraoches.
