### ISSUE TITLE
first page is skipped, last page doesn't have a timer

### ISSUE THREAD

**Issue by abiemann** [siralam/LoopingViewPager#6]
my viewpager has 4 pages: indexes 0,1,2,3

It seems that LoopingViewPager starts at page[1] (I expected page[0]), then page[2], then it skips the timer on page[3] and goes directly back to page[1]

usage in XML:

                    <com.asksira.loopingviewpager.LoopingViewPager
                        android:id="@+id/viewPager_info_screens"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:background="@drawable/shape_rect_round_corners_white"
                        android:layout_margin="5dp"
                        android:elevation="5dp"
                        app:isInfinite="true"
                        app:autoScroll="true"
                        app:scrollInterval="3000"/>

in Java:

        LoopingViewPager mPager = findViewById(R.id.viewPager_info_screens);
        mPagerAdapter = new ScreenSlidePagerAdapter(getSupportFragmentManager());
        mPager.setAdapter(mPagerAdapter);

**Comment by siralam** [comment]
Yes, indeed, as long as you have set `isInfinite` to true. If it is infinite, page[0] and page[3] are just dummies of page[2] and page[1] correspondingly (That means there are only 2 pages from the point of view of user)
